Repository AY2324S2-CS2103T-W13-4/tp, pull requests merged in 2024-03, with the labels that each got.

#17 Update Abdul Khaliq's AboutUs
  docs/AboutUs.md
  docs/images/github_breezetall.png
  docs/images/github_yskie.png
Labels: documentation

#19 Update Dinh Tran Hai Chien's AboutUs Page
  docs/AboutUs.md
  docs/images/kaya3842.png
Labels: documentation

#21 Update Chin Herng's AboutUs page
  docs/AboutUs.md
  docs/images/chin-herng.png
Labels: documentation

#24 Update product scope and user stories in developer guide
  docs/DeveloperGuide.md
Labels: documentation

#26 Update Non-Functional Requirement in DG
  docs/DeveloperGuide.md
Labels: documentation

#34 Add personal tasks
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/TaskList.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/storage/JsonSerializableTaskList.java
  src/main/java/seedu/address/storage/JsonTaskListStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/TaskListStorage.java
  src/test/data/JsonTaskListStorageTest/validTaskList.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/TaskListTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/storage/JsonSerializableTaskListTest.java
  src/test/java/seedu/address/storage/JsonTaskListStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/TaskUtil.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: type.Story, Priority.High

#36 Assign Tasks to Persons
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AssignCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TaskList.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AssignCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/AssignCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement, Priority.Medium

#39 Adding list command
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ListTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TaskList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/java/seedu/address/ui/TaskListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TaskListCard.fxml
  src/main/resources/view/TaskListPanel.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ListTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: enhancement

#40 Implement mark and unmark for tasks
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/MarkTaskCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/MarkTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/UnmarkTaskCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TaskList.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskDescription.java
  src/main/java/seedu/address/model/task/TaskName.java
  src/main/java/seedu/address/model/task/TaskStatus.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/TaskListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/AssignCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/AddTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/MarkTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UnmarkTaskCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/TaskListTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/storage/JsonSerializableTaskListTest.java
  src/test/java/seedu/address/storage/JsonTaskListStorageTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TaskUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: enhancement

#44 Clear Tasks of Persons
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ClearTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ClearTaskCommandParser.java
  src/test/java/seedu/address/logic/commands/ClearTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ClearTaskCommandParserTest.java
Labels: enhancement

#48 Branch task deadline
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskDeadline.java
  src/main/java/seedu/address/model/task/TaskDescription.java
  src/main/java/seedu/address/model/task/TaskName.java
  src/main/java/seedu/address/model/task/TaskStatus.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TaskListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/task/TaskDeadlineTest.java
  src/test/java/seedu/address/model/task/TaskDescriptionTest.java
  src/test/java/seedu/address/model/task/TaskNameTest.java
  src/test/java/seedu/address/model/task/TaskStatusTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
Labels: enhancement, type.Story

#49 Add Priority
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/MarkTaskCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TaskList.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskPriority.java
  src/main/java/seedu/address/model/util/Priority.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/TaskListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/data/JsonTaskListStorageTest/validTaskList.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/task/TaskPriorityTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TaskUtil.java
Labels: enhancement, type.Story

#51 Update to user guide
  docs/UserGuide.md
  docs/images/UI_v1.3a.png
  docs/images/findAlexDavidResult_v1.3a.PNG
  docs/images/helpMessage_v1.3a.PNG
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/TaskListCard.fxml
Labels: documentation

#52 Branch find tasks
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/FindTaskCommand.java
  src/main/java/seedu/address/logic/commands/MarkTaskCommand.java
  src/main/java/seedu/address/logic/commands/UnassignCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindTaskCommandParser.java
  src/main/java/seedu/address/model/task/TaskNameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/FindTaskCommandParserTest.java
  src/test/java/seedu/address/model/task/TaskNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: type.Story

#53 Update to developer guide for the proposed implementation
  build.gradle
  docs/DeveloperGuide.md
  docs/diagrams/GroupingState0.puml
  docs/diagrams/GroupingState1.puml
  docs/diagrams/GroupingState2.puml
  docs/package-lock.json
  docs/package.json
  src/main/java/seedu/address/MainApp.java
Labels: documentation
