Repository AY2324S2-CS2103T-W13-4/tp, pull requests merged in 2024-04, with the labels that each got.

#54 Update to developer guide for the logic and redo/undo commands
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoSequenceDiagram-Logic.puml
  docs/diagrams/UndoSequenceDiagram-Model.puml
Labels: documentation

#55 Update to user guide for the assign, unassign and cleartask commands
  docs/UserGuide.md
Labels: documentation

#56 Update to developer guide for the model component
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: documentation

#57 Update developer guide for UI
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
Labels: documentation

#58 Update priority
  src/main/java/seedu/address/logic/commands/MarkTaskCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TaskList.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskDescription.java
  src/main/java/seedu/address/model/task/TaskPriority.java
  src/main/java/seedu/address/model/task/TaskStatus.java
  src/test/java/seedu/address/logic/commands/MarkTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/TaskListTest.java
  src/test/java/seedu/address/model/task/TaskPriorityTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
Labels: enhancement

#59 The Edit Task Command
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditTaskCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TaskList.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskPriority.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/FindTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/EditTaskCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/EditTaskDescriptorBuilder.java
Labels: enhancement, type.Story, Priority.High

#61 Add edit task command into the user guide.
  build.gradle
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/MarkTaskCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkTaskCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TaskList.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/testutil/EditTaskDescriptorBuilder.java
Labels: documentation

#62 Update to UI
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/TaskListPanel.fxml
Labels: enhancement

#64 Update User Guide for findtask command.
  docs/UserGuide.md
Labels: documentation

#63 Update Developer Guide for the Storage component
  docs/DeveloperGuide.md
  docs/diagrams/StorageClassDiagram.puml
Labels: documentation

#65 Mass Ops
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/MarkTaskCommand.java
  src/main/java/seedu/address/logic/commands/UnassignCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkTaskCommand.java
  src/main/java/seedu/address/logic/parser/AssignCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/UnassignCommandParser.java
  src/main/java/seedu/address/logic/parser/UnmarkTaskCommandParser.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskDeadline.java
  src/main/java/seedu/address/model/task/TaskDescription.java
  src/main/java/seedu/address/model/task/TaskName.java
  src/main/java/seedu/address/model/task/TaskPriority.java
  src/main/java/seedu/address/model/task/TaskStatus.java
  src/test/java/seedu/address/logic/commands/AssignCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/EditTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/UnassignCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/AssignCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MarkTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UnassignCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UnmarkTaskCommandParserTest.java
  src/test/java/seedu/address/model/task/TaskDeadlineTest.java
  src/test/java/seedu/address/model/task/TaskDescriptionTest.java
  src/test/java/seedu/address/model/task/TaskNameTest.java
  src/test/java/seedu/address/model/task/TaskPriorityTest.java
  src/test/java/seedu/address/model/task/TaskStatusTest.java
Labels: enhancement

#66 Update Ui image
  docs/UserGuide.md
  docs/images/Ui.png
  docs/index.md
Labels: documentation

#67 Update to implementation of grouping
  docs/DeveloperGuide.md
  docs/diagrams/GroupingState3puml
Labels: documentation

#129 Fix overflow issue with UI
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/TaskListCard.fxml
Labels: UI.bug

#130 Fix task to string issue
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/task/Task.java
Labels: bug, AB3.bug

#131 Fix priority bug
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
Labels: TeamTracker.bug

#133 Update unmarktask test
  src/test/java/seedu/address/logic/commands/UnmarkTaskCommandTest.java
Labels: enhancement

#136 Documentation of Mass Ops
  docs/UserGuide.md
Labels: documentation

#137 Add 'Planned Enhancements' appendix
  docs/DeveloperGuide.md
Labels: documentation

#135 Reformat user guide
  docs/UserGuide.md
  docs/images/Properties.png
  docs/images/Terminal_start.png
  docs/images/UI_addtask.png
  docs/images/UI_annotated.png
  docs/images/UI_assign.png
  docs/images/UI_deletetask.png
  docs/images/UI_marktask.png
  docs/images/UI_v1.3.1.png
  docs/images/Ui.png
Labels: documentation

#138 Tweak Usage Messages
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/MarkTaskCommand.java
  src/main/java/seedu/address/logic/commands/UnassignCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkTaskCommand.java
  src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkTaskCommandTest.java
Labels: Priority.Low

#139 Fix formatting bugs in UG
  docs/UserGuide.md
Labels: documentation

#141 Update for print format
  docs/UserGuide.md
  docs/images/findAlexDavidResult_v1.4.png
Labels: documentation

#149 Fix grammar mistake
  docs/UserGuide.md
Labels: documentation

#151 Fix grammar
  docs/UserGuide.md
Labels: documentation
